### PR TITLE
Initiate PR Template Format

### PR DESCRIPTION
**Pull request by jsmazorra**

### CODE REVIEW

**Comment by jsmazorra** [comment]
Sample of Usage
# Description
Modifications into the PR as a guidance on how to use it in the future.
### Type of change
 - [x] New feature (non-breaking change which adds functionality)

### Change Status
 - [ ] Complete, ready to review and merge
 - [x] Incomplete/work-in-progress, PR is for discussion/feedback
  
### Has This Been Tested
 - [ ] Yes
 - [ ] No
 - [x] Not necessary

# Checklist
 - [x] Received feedback from other team members
 - [x] I have performed a self-review of my own work
 - [ ] I have made corresponding changes according to feedback
 - [x] My changes generate no new warnings
 - [x] There are no merge conflicts

**Review by jessemarek — APPROVED** [review]
Great looking template checklist for PRs

**Review by JackRossProjects — APPROVED** [review]
Great template!

**Review by jengopockets — APPROVED** [review]
Looks good! Wondering what kind of testing data science will use?

**Pull request merged**
